### ISSUE TITLE
this._connection.eventNames() | TypeError not a function

### ISSUE THREAD

**Issue by bipinpaulbedi** [amqp/rhea-promise#20]
**Describe the bug**
Using @Azure/event-hubs client causes error
TypeError: this._connection.eventNames is not a function
    at Connection._initializeEventListeners (connection.js:613)
    at new Connection (connection.js:81)
    at Object.create (ConnectionContextBase.js:59)
    at Object.create (connectionContext.js:55)
    at new EventHubClient (eventHubClient.js:63)
    at Function.createFromConnectionString (eventHubClient.js:486)
    at Object.log (eventHubApi.js:7)
    at _callee$ (actions.js:35)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:288)
    at Generator.prototype.(:3000/anonymous function) [as next] (http://localhost:3000/static/js/24.chunk.js:9099:21)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)

**To Reproduce**
// event hub api
import { EventHubClient } from '@azure/event-hubs';

const EventHubApi = {
  log(data) {
    try {
      const client = EventHubClient.createFromConnectionString(
        <CONNECTION-STING>,<HUB-NAME>
      );
      client.send({ body: data });
    } catch (ex) {
      // eslint-disable-next-line no-console
      console.log('Event Hub Logging Failed');
      // eslint-disable-next-line no-console
      console.log(ex);
    }
  }
};

export default EventHubApi;

**Expected behavior**
No exception

**Package-version**: "@azure/event-hubs": "^1.0.7", "@azure/amqp-common": "^0.1.3","rhea-promise": "^0.1.7"
**node.js version**: Chrome Browser
**OS name and version**: Windows 10

**Additional context**
Potential Fix
    if (typeof this._connection.eventNames === "function") {
      log.eventHandler("[%s] rhea-promise 'connection' object is listening for events: %o " +
        "emitted by rhea's 'connection' object.", this.id, this._connection.eventNames());
    }

I don't have permission to create pull requests/branches

**Comment by bipinpaulbedi** [comment]
Created a pull request

https://github.com/amqp/rhea-promise/pull/21

**Comment by amarzavery** [comment]
@bipinpaulbedi - Something is amiss over here. 
Connection `extends` (nodejs) EventEmitter. Hence it is an event emitter too. `eventNames()` is a method on the EventEmitter class. Hence it is highly impossible for that method to not be present.
Here is the node.js EventEmitter [doc](https://nodejs.org/dist/latest-v10.x/docs/api/events.html#events_emitter_eventnames).

Your fix will certainly avoid the error that you are facing. However, I am not sure if you would actually be able to send messages. Since every entity in the library is an EventEmitter (node.js). Not sure if that EventEmitter is browser compatible.

Looks like you are using this in the browser. The library is not browserified.

**Comment by bipinpaulbedi** [comment]
The pull request #22 takes care of this... Issue is closed.
